services:
  catalogdb:
    container_name: catalog_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123Passrahil
      - POSTGRES_DB=Catalogdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
  
  catalog.api:
    container_name: catalog_api
    # command: ["dotnet", "Catalog.Api.dll"]
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=Catalogdb;User Id=postgres;Password=123Passrahil
    depends_on:
      - catalogdb 
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
