syntax = "proto3";

option csharp_namespace = "Discount.Grpc";

package discount;

//discount service defination
service DiscountProtoService{
	//Discount Crud Operation
	rpc GetDiscount (GetDiscountRequest) returns (CouponModel);
	rpc CreateDiscount (CreateDiscountRequest) returns (CouponModel);
	rpc UpdateDiscount (UpdateDiscountRequest) returns (CouponModel);
	rpc DeleteDiscount (DeleteDiscountRequest) returns (DeleteDiscountResponse);
}
message GetDiscountRequest {
	string ProductName = 1;
}
message CouponModel {
	int32 Id = 1; //here 1 2 3 4 are order of parameters
	string ProductName = 2;
	string Description = 3;
	int32 Amount = 4;
}
message CreateDiscountRequest {
	CouponModel Coupon = 1;
}
message UpdateDiscountRequest {
	CouponModel Coupon = 1;
}
message DeleteDiscountRequest {
	string ProductName = 1;
}
message DeleteDiscountResponse {
	bool Success = 1;
	
}

